server:
  port: 8080

spring:
  datasource:
   name: tasks
   url: jdbc:h2:file:~/tasks
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
